# File: .github/workflows/tests.yml

name: Run Tests

on:
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: python -m unittest tests.test_unit_all
      
    - name: Run functional tests
      env:
        MONGODB_URI: mongodb://localhost:27017/test_db
        MONGODB_DB_NAME: test_db
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python -m unittest tests.test_functional